baseurl = "http://kushdilip.github.io/blog/"
languageCode = "en-us"
title = "Welcome"
theme = "hugo-theme-crisp"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = false
disqus = "kushdilipblog"
disqusShortname = "kushdilipblog"
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "kushdilip's blog"
  author = "dilip"
