baseurl = "http://kushdilip.github.io/blog/"
languageCode = "en-us"
title = "KUSHDILIP"
theme = "hugo-icarus-theme"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
disqus = "kushdilipblog"
disqusShortname = "kushdilipblog"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "kushdilip's blog"
  author = "dilip"
  date_format = "2006-01-02"
